version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./backend/storage:/var/www/storage
    restart: unless-stopped
    networks:
      - docavailable-network

  # Optional: Frontend web service
  # Uncomment if you want to serve the React Native web version
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_API_URL=http://backend:8000
  #   restart: unless-stopped
  #   networks:
  #     - docavailable-network

networks:
  docavailable-network:
    driver: bridge 