version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      # Neon PostgreSQL Configuration
      - DB_CONNECTION=pgsql_simple
      - DB_HOST=ep-hidden-brook-aemmopjb-pooler.c-2.us-east-2.aws.neon.tech
      - DB_PORT=5432
      - DB_DATABASE=neondb
      - DB_USERNAME=neondb_owner
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=postgresql://neondb_owner:${DB_PASSWORD}@ep-hidden-brook-aemmopjb-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&options=endpoint%3Dep-hidden-brook-aemmopjb
      - DB_CONNECT_TIMEOUT=10
      - DB_SOCKET_TIMEOUT=30
      - DB_PERSISTENT=false
    volumes:
      - ./backend/storage:/var/www/storage
    restart: unless-stopped
    networks:
      - docavailable-network

  # Optional: Frontend web service
  # Uncomment if you want to serve the React Native web version
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_API_URL=http://backend:8000
  #   restart: unless-stopped
  #   networks:
  #     - docavailable-network

networks:
  docavailable-network:
    driver: bridge 