services:
  - type: web
    name: docavailable-backend
    env: docker
    buildCommand: 
    startCommand: 
    rootDir: backend
    dockerfilePath: dockerfile
    envVars:
      - key: APP_NAME
        value: DocAvailable
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: error
      - key: CACHE_STORE
        value: database
      - key: CACHE_PREFIX
        value: laravel-cache-
      - key: QUEUE_CONNECTION
        value: database
      - key: QUEUE_FAILED_DRIVER
        value: database-uuids
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: FILESYSTEM_DISK
        value: local
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ${DB_DATABASE}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_SSLMODE
        value: require
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: MEMCACHED_HOST
        value: 127.0.0.1
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: "hello@example.com"
      - key: MAIL_FROM_NAME
        value: "${APP_NAME}"
      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        value: ""
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: ""
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false
      - key: PUSHER_APP_ID
        value: ""
      - key: PUSHER_APP_KEY
        value: ""
      - key: PUSHER_APP_SECRET
        value: ""
      - key: PUSHER_HOST
        value: ""
      - key: PUSHER_PORT
        value: 443
      - key: PUSHER_SCHEME
        value: https
      - key: PUSHER_APP_CLUSTER
        value: mt1
      - key: VITE_APP_NAME
        value: "${APP_NAME}"
      - key: VITE_PUSHER_APP_KEY
        value: "${PUSHER_APP_KEY}"
      - key: VITE_PUSHER_HOST
        value: "${PUSHER_HOST}"
      - key: VITE_PUSHER_PORT
        value: "${PUSHER_PORT}"
      - key: VITE_PUSHER_SCHEME
        value: "${PUSHER_SCHEME}"
      - key: VITE_PUSHER_APP_CLUSTER
        value: "${PUSHER_APP_CLUSTER}" 