name: docavailable-backend
services:
- name: laravel-backend
  source_dir: /backend
  github:
    repo: your-github-username/docavailable
    branch: main
  build_command: composer install --no-dev --optimize-autoloader --no-interaction
  run_command: bash scripts/start.sh
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: APP_NAME
    value: DocAvailable
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: false
  - key: APP_URL
    value: https://docavailable-backend.ondigitalocean.app
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: docavailable-db-do-user-25123073-0.h.db.ondigitalocean.com
  - key: DB_PORT
    value: "25060"
  - key: DB_DATABASE
    value: defaultdb
  - key: DB_USERNAME
    value: doadmin
  - key: DB_PASSWORD
    value: ${DB_PASSWORD}
  - key: DB_SSLMODE
    value: require
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: sync
  - key: LOG_CHANNEL
    value: stack
  - key: FILESYSTEM_DISK
    value: spaces
  - key: SPACES_KEY
    value: ${SPACES_KEY}
  - key: SPACES_SECRET
    value: ${SPACES_SECRET}
  - key: SPACES_ENDPOINT
    value: ${SPACES_ENDPOINT}
  - key: SPACES_REGION
    value: ${SPACES_REGION}
  - key: SPACES_BUCKET
    value: ${SPACES_BUCKET}
  - key: PAYCHANGU_API_KEY
    value: ${PAYCHANGU_API_KEY}
  - key: PAYCHANGU_SECRET_KEY
    value: ${PAYCHANGU_SECRET_KEY}
  - key: PAYCHANGU_MERCHANT_ID
    value: ${PAYCHANGU_MERCHANT_ID}
  - key: PAYCHANGU_WEBHOOK_SECRET
    value: ${PAYCHANGU_WEBHOOK_SECRET}
  - key: PAYCHANGU_ENVIRONMENT
    value: ${PAYCHANGU_ENVIRONMENT}
  - key: DEEPSEEK_API_KEY
    value: ${DEEPSEEK_API_KEY}

databases:
- name: docavailable-db
  engine: PG
  version: "15"
  production: false
