name: docavailable-backend
services:
- name: laravel-backend
  source_dir: /backend
  github:
    repo: your-github-username/docavailable
    branch: main
  run_command: php artisan serve --host=0.0.0.0 --port=$PORT
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: APP_NAME
    value: DocAvailable
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: false
  - key: APP_URL
    value: https://docavailable-backend.ondigitalocean.app
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: docavailable-db-do-user-25123073-0.h.db.ondigitalocean.com
  - key: DB_PORT
    value: "25060"
  - key: DB_DATABASE
    value: defaultdb
  - key: DB_USERNAME
    value: doadmin
  - key: DB_PASSWORD
    value: your_database_password_here
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: sync
  - key: LOG_CHANNEL
    value: stack
  - key: DEEPSEEK_API_KEY
    value: your_deepseek_api_key_here
  - key: PAYCHANGU_API_KEY
    value: your_paychangu_api_key
  - key: PAYCHANGU_SECRET_KEY
    value: your_paychangu_secret_key
  - key: PAYCHANGU_MERCHANT_ID
    value: your_merchant_id
  - key: PAYCHANGU_WEBHOOK_SECRET
    value: your_webhook_secret
  - key: PAYCHANGU_ENVIRONMENT
    value: sandbox
  - key: SPACES_KEY
    value: your_spaces_key_here
  - key: SPACES_SECRET
    value: your_spaces_secret_here
  - key: SPACES_ENDPOINT
    value: https://nyc1.digitaloceanspaces.com
  - key: SPACES_REGION
    value: nyc1
  - key: SPACES_BUCKET
    value: docavailable-storage
  - key: FILESYSTEM_DISK
    value: spaces

databases:
- name: docavailable-db
  engine: PG
  version: "15"
  production: false
